name: flutter_finalapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^3.13.0       # imprescindível para inicializar o Firebase
  firebase_auth: ^5.5.2      # para autenticação
  cloud_firestore: ^5.6.6    # para Firestore
  google_sign_in: ^6.1.5
  firebase_analytics: ^11.4.5
  crypto: ^3.0.1
  firebase_storage: ^12.4.5
  intl: ^0.18.1
  file_picker: ^10.1.2
  http: ^0.13.6
  table_calendar: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
