// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQwsrQTA7zLkkGJjZTJRopnTzpqh1_Kts',
    appId: '1:916688014366:android:104d045a9b12ee9f23320f',
    messagingSenderId: '916688014366',
    projectId: 'flutterfinalapp-ed3b2',
    storageBucket: 'flutterfinalapp-ed3b2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA13_kssJrA7rUc6EiZerzoYjAWmZIUSdQ',
    appId: '1:916688014366:web:e667f7cc91bfa8ba23320f',
    messagingSenderId: '916688014366',
    projectId: 'flutterfinalapp-ed3b2',
    authDomain: 'flutterfinalapp-ed3b2.firebaseapp.com',
    storageBucket: 'flutterfinalapp-ed3b2.firebasestorage.app',
    measurementId: 'G-64DYZ6TM9M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMOSkqs44i6ql11vNCwzlUfu_Sjx89ilc',
    appId: '1:916688014366:ios:f1f7b4a4d17cf4c123320f',
    messagingSenderId: '916688014366',
    projectId: 'flutterfinalapp-ed3b2',
    storageBucket: 'flutterfinalapp-ed3b2.firebasestorage.app',
    iosClientId: '916688014366-6eruc4di3i6effmtf0cmlakmtda8aps4.apps.googleusercontent.com',
    iosBundleId: 'com.flutterfinalappios',
  );

}